### ISSUE TITLE
Unable to add email recipients to report

### ISSUE THREAD

**Issue by lbsou** [Cacti/plugin_reportit#24] opened 2018-06-29 13:00 UTC
Cacti 1.1.38
Reportit git clone develop branch 2018-06-28

When I try to add an email recipients in a report, I hit "add" then it just bring me to the list of report...

Nothing in the logs.

Another thing that is curious, at the bottom of the email tab, there is no "save" button like in other tabs.

Thank you!

**Comment by netniV** [comment] 2018-06-29 14:26
Check both the cacti logs and the apache error logs.  Another thing to check is that your temporary folder has write acesss for the website user (but that usually has more issue with file uploads than anything else).

**Comment by lbsou** [comment] 2018-06-29 14:32
Nothing in cacti logs with report module and report php file in debug mode
Nothing in apache error.log

Not sure to understand the temporary folder validation...

**Comment by gmourani** [comment] 2018-09-06 15:02
For me with the latest version of reportit (1.0.2), I can add the user email but he doesn't appears in the list and nothing in the Apache log file !

<img width="1049" alt="screen shot 2018-09-06 at 11 01 41 am" src="https://user-images.githubusercontent.com/20328799/45166102-438fbd00-b1c4-11e8-8d7c-21a5c13b1b4b.png">

**Comment by optimuscream** [comment] 2018-09-19 08:55
Same issue for me. I can add email address manually directly from  the  database. 

INSERT INTO plugin_reportit_recipients (id, report_id, email, name) VALUES('21757', '1', 'email.address@domain.com', 'name' );

But when I run the report, nothing sent. No log.

**Comment by netniV** [comment] 2018-09-19 13:04
Check that the auto email is actually enabled in the Settings -> ReportIt tab.  You also need to have it enabled within the report definition.  To query directly on the db, do the following:

```sql
select * from settings where name = 'reportit_email'
select id, auto_email from plugin_reportit_reports where id = <id>
```
Replace `<id>` with the id number of the report when you edit it.

**Comment by optimuscream** [comment] 2018-09-20 01:40
Helo ,

Yes the first place I check is Reportit tab email settings. It is checked.
I also run threshold alert in this cacti and email alert working well

```
SELECT * FROM `plugin_reportit_data_items`;
+-------+-----------+-------------+-----------+---------+------------+----------+----------------+
| id    | report_id | description | start_day | end_day | start_time | end_time | timezone       |
+-------+-----------+-------------+-----------+---------+------------+----------+----------------+
| 21757 |         1 |             | Monday    | Sunday  | 00:00:00   | 24:00:00 |  THA (GMT+07 ) |
+-------+-----------+-------------+-----------+---------+------------+----------+----------------+

select * from settings where name = 'reportit_email';
+----------------+-------+
| name           | value |
+----------------+-------+
| reportit_email | on    |
+----------------+-------+
1 row in set (0.00 sec)


select id, auto_email from plugin_reportit_reports where id = 1;
+----+------------+
| id | auto_email |
+----+------------+
|  1 | 1          |
+----+------------+
1 row in set (0.00 sec)
```
Cacti version 1.1.38
Latest reportit plugin cloned from github.

Thanks in advance.

**Comment by ikorzha** [comment] 2018-09-23 13:55
netniV, I can confirm with other users that adding email to report doesn't function and that is a very important piece of this plugin that myself and others rely on.
Back in a day of reportIT 0.8 my brother did fix this functionality, I can share with you the old  0.8 reportit it has functioning code that you can extract this email portion fix or you can apply fix of your own.
Thank you in advance for your comments.

**Comment by netniV** [comment] 2018-09-23 14:27
You could but I need to make it work with 1.x so there is probably little point.  At this point I need to figure out how to actually create a working report since I never really used ReportIT until this week ;-)

One of the joys of being a developer, you seem to know the code before you know the product.

**Comment by ikorzha** [comment] 2018-09-23 14:58
2 Things netniV, I believe the email code from 0.8.x can help as I believe it was missing in the first place from 0.8x branch and of course still missing here too on 1.0.2..
When it comes to reportIT teaching the ropes, I will be happy to provide you with learning session over Skype for business meeting or webex, it would probably take only 10-15min.
I am actually uniquely positioned for that task as I have a fully working installation of reportIT on 0.8 branch as well as 1.0.2 branch to compare and contrast, so you can see non working features and how it should be..

Just let me if you a time of your convenience and I will send you private meeting invite I am in US Eastern time zone..

**Comment by netniV** [comment] 2018-09-23 15:23
Thanks for the offer, if I need it I'll take you up on it.  It would have to be webex as I have a personal license for teamviewer and that gets invalidated by pro ones.  

Attach the code here and I will attempt to do a diff between the 0.8 version I can find and what you have.  That, as you say, may be a missing piece.

**Comment by ikorzha** [comment] 2018-09-23 15:44
Here attached is cc_reports.php from 0.8 that was previously fixed, which= reports.php in reportit 1.0.2

Please see if you can extract relevant piece of code to this problem.

This is how this working piece looked like in reportIT 0.8:
[cc_reports.txt](https://github.com/Cacti/plugin_reportit/files/2408867/cc_reports.txt)

![image](https://user-images.githubusercontent.com/11211789/45929891-e6b33700-bf25-11e8-9cb8-3bcac7798853.png)

**Comment by netniV** [comment] 2018-09-23 17:34
Bad news is that from what I can see, that functionality is still there, so it will have to be a full debug session to work it out.

**Comment by ikorzha** [comment] 2018-09-23 19:21
Understood, we have to patiently wait. Thank you in advance.

**Comment by optimuscream** [comment] 2018-09-24 02:00
Hi Mark (netniV)  .. really appreciate your effort . Waiting for the result. Thanks

**Comment by netniV** [comment] 2018-10-01 11:47
So, I believe I amended the scheduling options, but then found that it wouldn't work.  The reason being that there is a flag "reportit_operator" which determines if scheduling appears under the "General" or "Admin" tabs.  I fixed up the general one, not the admin.  However, I think both need more work so a fix for that will be coming shortly.

**Comment by netniV** [comment] 2018-10-01 12:34
OK, so a new update has been pushed to the 1.1.0 that's on the develop branch.  This should now allow the saving of schedule fields whether they are on the general or admin tab of the report.  Additionally, there is now a setting under Console->Configuration->Settings->Reports called `Allow scheduling by Operators` which shifts which tab the scheduling appears.

**Comment by ikorzha** [comment] 2018-10-02 01:23
I confirm that report scheduling portion now working as designed and "report scheduling configuration" now get saved.
Next issue in scheduling is email delivery, entered data into form doesn't get saved:
Here is just a quick animated gif for reference.
![adding-email](https://user-images.githubusercontent.com/11211789/46324180-3b0e8480-c5c0-11e8-90d0-217b089baeaa.gif)

**Comment by netniV** [comment] 2018-10-02 13:23
So this would appear to be because the form is not sending back the custom attribute for the Add button to notify the backend to add a recipient.  I'll have to see what can be done, though it may be like adding variables etc, where it's on a separate window.

**Comment by rchen14b** [comment] 2018-10-02 21:55
@netniV 

Hey Mark,

So the email function is basically not working yet?

**Comment by netniV** [comment] 2018-10-02 22:08
You can manually add recipients but you can't through the webform.  To manually add:

```
INSERT INTO `plugin_reportit_recipients` (`id`, `report_id`, `email`, `name`) VALUES (NULL, '999', 'netniv@cacti.net', 'Mark Brugnoli-Vinten')
```

Just replace the 999 with the report's ID (found when editing it) and the obvious email/name

This is a workaround until the add functionality gets repaired.

**Comment by rchen14b** [comment] 2018-10-03 14:26
@netniV 

Thanks. I was able to add a email address to it. But it seems like even I added my email, when I run a report, it still won't send the email. Any workaround to approach this one?

**Comment by rchen14b** [comment] 2018-10-03 14:40
@netniV 

Updated to 1.1.2, now I can't get into reports any more.
![image](https://user-images.githubusercontent.com/13096569/46417968-62646f00-c6f0-11e8-9755-64d9ec4f5083.png)

**Comment by netniV** [comment] 2018-10-03 14:43
Can you give me the error that is occurring?  I was running fine.

**Comment by rchen14b** [comment] 2018-10-03 14:48
> Can you give me the error that is occurring? I was running fine.

Nothing on the log. I tried uninstall and reinstall no luck.

**Comment by rchen14b** [comment] 2018-10-03 15:00
> Can you give me the error that is occurring? I was running fine.

Reverted back to 1.1.1. Everything work again.

**Comment by netniV** [comment] 2018-10-03 15:05
Error 500 means there will be a log entry somewhere.  If it's not appearing in the cacti log, it should be appearing in the apache log

**Comment by rchen29** [comment] 2018-10-03 15:08
> Error 500 means there will be a log entry somewhere. If it's not appearing in the cacti log, it should be appearing in the apache log

How can I check apache log? I can check it for you. I'm on 1.1.1, everything work fine on this version.

**Comment by rchen14b** [comment] 2018-10-03 15:11
> Error 500 means there will be a log entry somewhere. If it's not appearing in the cacti log, it should be appearing in the apache log

 - - [03/Oct/2018:09:47:10 -0500] "GET /cacti/index.php HTTP/1.1" 200 30113 "http://MY_CACTI/cacti/clog.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
 - - [03/Oct/2018:09:47:12 -0500] "GET /cacti/user_domains.php HTTP/1.1" 200 25218 "http://MY_CACTI/cacti/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
 - - [03/Oct/2018:09:47:13 -0500] "GET /cacti/plugins.php HTTP/1.1" 200 27467 "http://MY_CACTI/cacti/user_domains.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
 - - [03/Oct/2018:09:47:15 -0500] "GET /cacti/plugins.php?mode=install&id=reportit HTTP/1.1" 302 - "http://MY_CACTI/cacti/plugins.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
 - - [03/Oct/2018:09:47:16 -0500] "GET /cacti/plugins.php HTTP/1.1" 200 27547 "http://MY_CACTI/cacti/plugins.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
 - - [03/Oct/2018:09:47:17 -0500] "GET /cacti/plugins.php?mode=enable&id=reportit HTTP/1.1" 302 - "http://MY_CACTI/cacti/plugins.php?mode=install&id=reportit" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
 - - [03/Oct/2018:09:47:17 -0500] "GET /cacti/plugins.php HTTP/1.1" 200 27838 "http://MY_CACTI/cacti/plugins.php?mode=install&id=reportit" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
 - - [03/Oct/2018:09:47:20 -0500] "GET /cacti/plugins/reportit/reports.php HTTP/1.1" 500 - "http://MY_CACTI/cacti/plugins.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
 - - [03/Oct/2018:09:47:22 -0500] "GET /cacti/plugins/reportit/view.php HTTP/1.1" 500 - "http://MY_CACTI/cacti/plugins.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
 - - [03/Oct/2018:09:47:26 -0500] "GET /cacti/ HTTP/1.1" 200 30406 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
 - - [03/Oct/2018:09:47:28 -0500] "GET /cacti/clog.php HTTP/1.1" 200 150780 "http://MY_CACTI/cacti/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
 - - [03/Oct/2018:09:47:31 -0500] "GET /cacti/clog.php?rfilter=&reverse=1&refresh=60&message_type=-1&tail_lines=500&filename=cacti.log&header=false HTTP/1.1" 200 142619 "http://MY_CACTI/cacti/clog.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
 - - [03/Oct/2018:09:47:35 -0500] "GET /cacti/index.php HTTP/1.1" 200 30406 "http://MY_CACTI/cacti/clog.php?rfilter=&reverse=1&refresh=60&message_type=-1&tail_lines=500&filename=cacti.log&" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
 - - [03/Oct/2018:09:47:36 -0500] "GET /cacti/plugins/reportit/reports.php HTTP/1.1" 500 - "http://MY_CACTI/cacti/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
 - - [03/Oct/2018:09:48:11 -0500] "GET /cacti/plugins/reportit/reports.php HTTP/1.1" 500 - "http://MY_CACTI/cacti/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
 - - [03/Oct/2018:09:48:11 -0500] "GET /cacti/plugins/reportit/reports.php HTTP/1.1" 500 - "http://MY_CACTI/cacti/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
 - - [03/Oct/2018:09:48:12 -0500] "GET /cacti/plugins/reportit/reports.php HTTP/1.1" 500 - "http://MY_CACTI/cacti/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
 - - [03/Oct/2018:09:48:12 -0500] "GET /cacti/plugins/reportit/reports.php HTTP/1.1" 500 - "http://MY_CACTI/cacti/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
 - - [03/Oct/2018:09:48:15 -0500] "GET /cacti/settings.php HTTP/1.1" 200 51595 "http://MY_CACTI/cacti/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
 - - [03/Oct/2018:09:48:16 -0500] "GET /cacti/settings.php?tab=reports&header=false HTTP/1.1" 200 36431 "http://MY_CACTI/cacti/settings.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
 - - [03/Oct/2018:09:48:26 -0500] "POST /cacti/settings.php?tab=reports&header=false HTTP/1.1" 302 - "http://MY_CACTI/cacti/settings.php?tab=reports&" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
 - - [03/Oct/2018:09:48:26 -0500] "GET /cacti/settings.php?header=false&tab=reports HTTP/1.1" 200 36466 "http://MY_CACTI/cacti/settings.php?tab=reports&" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"



Could that be browser cache issue?

**Comment by netniV** [comment] 2018-10-03 15:24
So I have installed 1.1.2 and found an issue where the templates table wasn't being generated if it didn't already exist.  This is due to a bug I've found with the api code for creating a plugin table.  So, I've made a workaround.  However, I'm not sure that would affect you but try the latest download from dev.

**Comment by rchen14b** [comment] 2018-10-03 15:53
> So I have installed 1.1.2 and found an issue where the templates table wasn't being generated if it didn't already exist. This is due to a bug I've found with the api code for creating a plugin table. So, I've made a workaround. However, I'm not sure that would affect you but try the latest download from dev.

Thanks. I will give a try.

**Comment by rchen14b** [comment] 2018-10-03 17:25
> > So I have installed 1.1.2 and found an issue where the templates table wasn't being generated if it didn't already exist. This is due to a bug I've found with the api code for creating a plugin table. So, I've made a workaround. However, I'm not sure that would affect you but try the latest download from dev.
> 
> Thanks. I will give a try.

Still have this issue, even with a different browser.
![image](https://user-images.githubusercontent.com/13096569/46427585-6b146f80-c707-11e8-9be3-6ee93a5c5ff4.png)

**Comment by rchen14b** [comment] 2018-10-03 17:28
@netniV 

I think I found the log:
[Wed Oct 03 12:26:45.689759 2018] [php7:warn] [pid 27148] [client MY_IP:7268] PHP Warning:  include(): Failed opening './include/global.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/cacti/include/auth.php on line 27, referer: http://Cacti_IP/cacti/user_group_admin.php?action=edit&id=1&tab=realms
[Wed Oct 03 12:26:45.689908 2018] [php7:error] [pid 27148] [client MY_IP:7268] PHP Fatal error:  Uncaught Error: Call to undefined function get_cacti_version() in /var/www/html/cacti/include/auth.php:30\nStack trace:\n#0 /var/www/html/cacti/plugins/reportit/reports.php(25): require_once()\n#1 {main}\n  thrown in /var/www/html/cacti/include/auth.php on line 30, referer: http://Cacti_IP/cacti/user_group_admin.php?action=edit&id=1&tab=realms

**Comment by netniV** [comment] 2018-10-03 17:41
Is the plugin enabled?

**Comment by netniV** [comment] 2018-10-03 17:41
No wait, that error is given by user_group_admin.php not by reportit.

**Comment by netniV** [comment] 2018-10-03 17:42
run this in the reportit directory:
```console
php -l view.php
```

**Comment by rchen14b** [comment] 2018-10-03 18:26
@netniV 

The plugin is enabled. Here is the output:
![image](https://user-images.githubusercontent.com/13096569/46430668-5cca5180-c70f-11e8-92bb-a2a057fc8f1b.png)

**Comment by rchen14b** [comment] 2018-10-03 18:27
@netniV 

HTTPD error regarding to this action:
[Wed Oct 03 13:21:18.927643 2018] [php7:warn] [pid 1419] [client MY_IP:11790] PHP Warning:  include(./include/global.php): failed to open stream: No such file or directory in /var/www/html/cacti/include/auth.php on line 27, referer: http://CACTI_IP/cacti/plugins.php
[Wed Oct 03 13:21:18.927735 2018] [php7:warn] [pid 1419] [client MY_IP:11790] PHP Warning:  include(): Failed opening './include/global.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/cacti/include/auth.php on line 27, referer: http://CACTI_IP/cacti/plugins.php
[Wed Oct 03 13:21:18.927888 2018] [php7:error] [pid 1419] [client MY_IP:11790] PHP Fatal error:  Uncaught Error: Call to undefined function get_cacti_version() in /var/www/html/cacti/include/auth.php:30\nStack trace:\n#0 **/var/www/html/cacti/plugins/reportit/reports.php(25):** require_once()\n#1 {main}\n  thrown in /var/www/html/cacti/include/auth.php on line 30, referer: http://CACTI_IP/cacti/plugins.php

**Comment by ikorzha** [comment] 2018-10-03 18:39
netniV I am getting the same errors as rchen29 has reported (ERROR 500) with the latest GIT build:
When I click Console ->Template->report:
![image](https://user-images.githubusercontent.com/11211789/46431479-ed0d9400-c719-11e8-8585-61871828ffc6.png)

[Wed Oct 03 14:34:18.771424 2018] [php7:error] [pid 26834] [client 172.18.40.255:53017] PHP Fatal error:  Uncaught Error: Call to undefined function get_cacti_version() in /var/www/html/include/auth.php:30\nStack trace:\n#0 /var/www/html/plugins/reportit/templates.php(25): require_once()\n#1 {main}\n  thrown in /var/www/html/include/auth.php on line 30, referer: https://cactione.aaa.com/utilities.php?action=view_logfile

**Comment by netniV** [comment] 2018-10-03 19:34
What version of Cacti are you two running? I think I know what the issue is now....

**Comment by rchen14b** [comment] 2018-10-03 19:42
> What version of Cacti are you two running? I think I know what the issue is now....

@netniV 
1.1.37

**Comment by ikorzha** [comment] 2018-10-03 20:02
I am on 1.1.38

**Comment by netniV** [comment] 2018-10-03 20:06
One minute and i'll have an update for you.

**Comment by netniV** [comment] 2018-10-03 20:08
Or I could just set the minimum requirement to 1.2 and be `evil` ;-)

**Comment by rchen14b** [comment] 2018-10-03 20:10
> Or I could just set the minimum requirement to 1.2 and be `evil` ;-)

😭 oh no

**Comment by netniV** [comment] 2018-10-03 20:11
OK fix should be up.  Let me know.

**Comment by rchen14b** [comment] 2018-10-03 20:17
@netniV 
[Wed Oct 03 15:15:32.878344 2018] [php7:warn] [pid 22175] [client MY_IP:23736] PHP Warning:  include(./include/global.php): failed to open stream: No such file or directory in /var/www/html/cacti/include/auth.php on line 27, referer: http://MY_IP/cacti/plugins.php
[Wed Oct 03 15:15:32.878423 2018] [php7:warn] [pid 22175] [client MY_IP:23736] PHP Warning:  include(): Failed opening './include/global.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/cacti/include/auth.php on line 27, referer: http://MY_IP/cacti/plugins.php
[Wed Oct 03 15:15:32.878529 2018] [php7:error] [pid 22175] [client MY_IP:23736] PHP Fatal error:  Uncaught Error: Call to undefined function get_cacti_version() in /var/www/html/cacti/include/auth.php:30\nStack trace:\n#0 /var/www/html/cacti/plugins/reportit/reports.php(25): require_once()\n#1 {main}\n  thrown in /var/www/html/cacti/include/auth.php on line 30, referer: http://MY_IP/cacti/plugins.php
[Wed Oct 03 15:15:52.088213 2018] [php7:warn] [pid 27351] [client MY_IP:23737] PHP Warning:  include(./include/global.php): failed to open stream: No such file or directory in /var/www/html/cacti/include/auth.php on line 27, referer: http://MY_IP/cacti/plugins.php
[Wed Oct 03 15:15:52.088301 2018] [php7:warn] [pid 27351] [client MY_IP:23737] PHP Warning:  include(): Failed opening './include/global.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/cacti/include/auth.php on line 27, referer: http://MY_IP/cacti/plugins.php
[Wed Oct 03 15:15:52.088397 2018] [php7:error] [pid 27351] [client MY_IP:23737] PHP Fatal error:  Uncaught Error: Call to undefined function get_cacti_version() in /var/www/html/cacti/include/auth.php:30\nStack trace:\n#0 /var/www/html/cacti/plugins/reportit/view.php(27): require_once()\n#1 {main}\n  thrown in /var/www/html/cacti/include/auth.php on line 30, referer: http://MY_IP/cacti/plugins.php
[Wed Oct 03 15:16:28.346672 2018] [php7:warn] [pid 14282] [client MY_IP:23871] PHP Warning:  include(./include/global.php): failed to open stream: No such file or directory in /var/www/html/cacti/include/auth.php on line 27, referer: http://MY_IP/cacti/plugins.php
[Wed Oct 03 15:16:28.346746 2018] [php7:warn] [pid 14282] [client MY_IP:23871] PHP Warning:  include(): Failed opening './include/global.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/cacti/include/auth.php on line 27, referer: http://MY_IP/cacti/plugins.php
[Wed Oct 03 15:16:28.346842 2018] [php7:error] [pid 14282] [client MY_IP:23871] PHP Fatal error:  Uncaught Error: Call to undefined function get_cacti_version() in /var/www/html/cacti/include/auth.php:30\nStack trace:\n#0 /var/www/html/cacti/plugins/reportit/reports.php(25): require_once()\n#1 {main}\n  thrown in /var/www/html/cacti/include/auth.php on line 30, referer: http://MY_IP/cacti/plugins.php


Still not let me in.

**Comment by ikorzha** [comment] 2018-10-03 20:21
Same problem for me: php error 500 still

[Wed Oct 03 16:18:59.538310 2018] [php7:warn] [pid 63193] [client 172.18.41.74:53520] PHP Warning:  include(./include/global.php): failed to open stream: No such file or directory in /var/www/html/include/auth.php on line 27, referer: https://cactione.aaa.com/utilities.php?action=view_logfile
[Wed Oct 03 16:18:59.538372 2018] [php7:warn] [pid 63193] [client 172.18.41.74:53520] PHP Warning:  include(): Failed opening './include/global.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/include/auth.php on line 27, referer: https://cactione.aaa.com/utilities.php?action=view_logfile
[Wed Oct 03 16:18:59.538450 2018] [php7:error] [pid 63193] [client 172.18.41.74:53520] PHP Fatal error:  Uncaught Error: Call to undefined function get_cacti_version() in /var/www/html/include/auth.php:30\nStack trace:\n#0 /var/www/html/plugins/reportit/reports.php(25): require_once()\n#1 {main}\n  thrown in /var/www/html/include/auth.php on line 30, referer: https://cactione.aaa.com/utilities.php?action=view_logfile

**Comment by netniV** [comment] 2018-10-03 20:24
Right, one second.

**Comment by netniV** [comment] 2018-10-03 20:24
You guys are making me go backwards ... I left 1.1.38 behind ages ago ;-)

**Comment by ikorzha** [comment] 2018-10-03 20:26
Easy for you to say I am afraid to move to 1.2 yet way to many unknowns..
Hell I can't even compile spine after 1.18x my pollers stop polling.. (correction it compiles fine just doesn't poll when installed on master server)

**Comment by netniV** [comment] 2018-10-03 20:27
Interesting, that shouldn't be an issue.  But what version is 1.18x?

**Comment by rchen14b** [comment] 2018-10-03 20:27
> Easy for you to say I am afraid to move to 1.2 yet way to many unknowns..
> Hell I can't even compile spine after 1.18x my pollers stop polling..

@netniV 

Haha, similar here. Since we can't affor to lose the stability,

**Comment by ikorzha** [comment] 2018-10-03 20:28
SPINE 1.1.18 Copyright 2004-2017 by The Cacti Group

**Comment by netniV** [comment] 2018-10-03 20:29
Oh.  Well you should open an issue on the spine repo for that then.  It shouldn't stop.  But I'd wait for 1.2, it changes the pollers so that may help.

But using your DB and 1.1.38, I can confirm error 500... let me check out why.

**Comment by netniV** [comment] 2018-10-03 20:36
OK and now we are back in action.  Sorry about that.

**Comment by netniV** [comment] 2018-10-03 20:37
Oh one other thing... for new issues, please create a new issue ;-) . Lets keep this thread to the bigger problem of trying to add recipients !

**Comment by rchen14b** [comment] 2018-10-03 20:43
> Oh one other thing... for new issues, please create a new issue ;-) . Lets keep this thread to the bigger problem of trying to add recipients !

Tried the new update, golden!

**Comment by netniV** [comment] 2018-10-03 20:44
Does the view report bit all work OK too?

**Comment by ikorzha** [comment] 2018-10-03 21:03
netniV, Error 500 has been fixed.
However report viewing is broken.
I will open a separate issue on it.

**Comment by netniV** [comment] 2018-10-04 02:14
This has now been resolved and committed to the development code.

**Closed as completed** 2018-10-04 02:14 UTC

**Comment by ikorzha** [comment] 2018-10-04 02:31
Tested this portion works thanks!

**Comment by rchen14b** [comment] 2018-10-04 03:01
Thanks you.

Regards,
Ruiyang(Ryan) Chen

**Comment by ikorzha** [comment] 2018-10-04 03:08
Just an FYI, I have opened issue #63 related to email delivery and archiving that is not currently functioning yet, even though email can now be successfully defined.
